name: Deploy to Railway

on:
  push:
    branches:
      - main  # Adjust if deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # - name: Build Docker image
      #   run: docker build -t my-app:latest .

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}
